node {
  name: "tensor_1_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/embed_tokens/embedding_pt_fwd_bf16/531_complex/reshape_0"
  op: "Reshape"
  input: "tensor_1_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_1_/placeholder/1  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "i32-1_7483  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_1_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 32064
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/embed_tokens/embedding_pt_fwd_bf16/531_complex/gather_bf16_2"
  op: "gather_bf16"
  input: "tensor_0_/placeholder/0"
  input: "model/embed_tokens/embedding_pt_fwd_bf16/531_complex/reshape_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [32064,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [197001216, 6144, 2]  |  data = 0, sizeInBytes = 197001216  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "i32-1_7483  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_1_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-3_7484  |  Sizes = [16,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isAliased = tensor_2_id_19713_model/embed_tokens/aten__embedding, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/embed_tokens/embedding_pt_fwd_bf16/531_complex/reshape_4"
  op: "Reshape"
  input: "model/embed_tokens/embedding_pt_fwd_bf16/531_complex/gather_bf16_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-3_7484  |  Sizes = [16,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isAliased = tensor_2_id_19713_model/embed_tokens/aten__embedding, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_id_19713_model/embed_tokens/aten__embedding  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "model/range_i32/532"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_3_id_19718_model/aten__arange  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
}
node {
  name: "tensor_4_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2050
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/expand_dims/535"
  op: "Reshape"
  input: "tensor_4_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_4_/placeholder/0  |  Sizes = [16,2050]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131200, 8200, 4]  |  data = 0, sizeInBytes = 131200  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_7_id_19766_model/aten__unsqueeze  |  Sizes = [16,1,1,2050]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131200, 8200, 8200, 8200, 4]  |  data = 0, sizeInBytes = 131200  |  isAliased = tensor_4_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/reshape/538"
  op: "Reshape"
  input: "model/range_i32/532"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_3_id_19718_model/aten__arange  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11_id_19738_model/aten__view  |  Sizes = [1,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isAliased = tensor_3_id_19718_model/aten__arange, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/range_i32/539"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_19732_model/aten__arange  |  Sizes = [2050]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8200, 4]  |  data = 0, sizeInBytes = 8200  |  isAliased = _reshaped_7658, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/greater_fwd_i32/540_complex/greater_fwd_i32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "model/range_i32/539"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_19732_model/aten__arange  |  Sizes = [2050]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8200, 4]  |  data = 0, sizeInBytes = 8200  |  isAliased = _reshaped_7658, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_7658  |  Sizes = [10,205]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8200, 820, 4]  |  data = 0, sizeInBytes = 8200  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
}
node {
  name: "model/greater_fwd_i32/540_complex/greater_fwd_i32_0_optimized"
  op: "greater_fwd_i32"
  input: "model/greater_fwd_i32/540_complex/greater_fwd_i32_0_reshape_TPC_out1"
  input: "model/reshape/538"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_7658  |  Sizes = [10,205]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8200, 820, 4]  |  data = 0, sizeInBytes = 8200  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_11_id_19738_model/aten__view  |  Sizes = [1,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isAliased = tensor_3_id_19718_model/aten__arange, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_7661  |  Sizes = [10,205]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2050, 205, 1]  |  data = 0, sizeInBytes = 2050  |  isAliased = tensor-7656, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "reshape_2_2"
  op: "Reshape"
  input: "model/greater_fwd_i32/540_complex/greater_fwd_i32_0_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_7661  |  Sizes = [10,205]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2050, 205, 1]  |  data = 0, sizeInBytes = 2050  |  isAliased = tensor-7656, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-7656  |  Sizes = [1,1,1,2050]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2050, 2050, 2050, 2050, 1]  |  data = 0, sizeInBytes = 2050  |  location = in DRAM  |  dramOffset = 0xa0000002080  |  "
    }
  }
}
node {
  name: "fusedTPCNode_15_2"
  op: "fused_kernel_0x231B57D2_27_bf16"
  input: "reshape_2_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-7656  |  Sizes = [1,1,1,2050]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2050, 2050, 2050, 2050, 1]  |  data = 0, sizeInBytes = 2050  |  location = in DRAM  |  dramOffset = 0xa0000002080  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18_id_19744_model/aten__unsqueeze  |  Sizes = [1,1,1,2050]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4100, 4100, 4100, 4100, 2]  |  data = 0, sizeInBytes = 4100  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  "
    }
  }
}
node {
  name: "tensor_27_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "fusedTPCNode_15_3"
  op: "fused_kernel_0x30BCDC60_28_f32"
  input: "fusedTPCNode_15_2"
  input: "model/expand_dims/535"
  input: "tensor_27_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_18_id_19744_model/aten__unsqueeze  |  Sizes = [1,1,1,2050]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4100, 4100, 4100, 4100, 2]  |  data = 0, sizeInBytes = 4100  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_7_id_19766_model/aten__unsqueeze  |  Sizes = [16,1,1,2050]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131200, 8200, 8200, 8200, 4]  |  data = 0, sizeInBytes = 131200  |  isAliased = tensor_4_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_27_/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32_id_19793_model/hpu__slice_insert  |  Sizes = [16,1,1,2050]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65600, 4100, 4100, 4100, 2]  |  data = 0, sizeInBytes = 65600  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
}
node {
  name: "tensor_32_id_19793_model/hpu__slice_insert"
  op: "OutputTensor"
  input: "fusedTPCNode_15_3"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2050
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "fusedTPCNode_15_0"
  op: "fused_kernel_0x58A689BE_25_f32"
  input: "model/embed_tokens/embedding_pt_fwd_bf16/531_complex/reshape_4"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_id_19713_model/embed_tokens/aten__embedding  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0xf0000000000  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_38_id_19799_model/0/input_layernorm/aten__pow  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/reduce_mean_multi_dim_fwd_f32/564_complex/reduce_mean_fwd_f32_0_complex/reduce_mean_fwd_f32_0"
  op: "reduce_mean_fwd_f32"
  input: "fusedTPCNode_15_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_19799_model/0/input_layernorm/aten__pow  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_42  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001080  |  "
    }
  }
}
node {
  name: "tensor_33_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "model/0/input_layernorm/add_fwd_f32/565_complex/add_fwd_f32_0"
  op: "add_fwd_f32"
  input: "model/0/input_layernorm/reduce_mean_multi_dim_fwd_f32/564_complex/reduce_mean_fwd_f32_0_complex/reduce_mean_fwd_f32_0"
  input: "tensor_33_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_42  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001080  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_33_/placeholder/0  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xb0000000000  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_43_id_19805_model/0/input_layernorm/hpu__add  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = _reshaped_7662, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/rsqrt_fwd_f32/566_complex/rsqrt_fwd_f32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "model/0/input_layernorm/add_fwd_f32/565_complex/add_fwd_f32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_43_id_19805_model/0/input_layernorm/hpu__add  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = _reshaped_7662, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_7662  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001100  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/rsqrt_fwd_f32/566_complex/rsqrt_fwd_f32_0_optimized"
  op: "rsqrt_fwd_f32"
  input: "model/0/input_layernorm/rsqrt_fwd_f32/566_complex/rsqrt_fwd_f32_0_reshape_TPC_out1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_7662  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001100  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_7663  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_44_id_19811_model/0/input_layernorm/aten__rsqrt, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/rsqrt_fwd_f32/566_complex/rsqrt_fwd_f32_0_reshape_TPC_out0"
  op: "StaticReshape"
  input: "model/0/input_layernorm/rsqrt_fwd_f32/566_complex/rsqrt_fwd_f32_0_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_7663  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_44_id_19811_model/0/input_layernorm/aten__rsqrt, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_44_id_19811_model/0/input_layernorm/aten__rsqrt  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001180  |  "
    }
  }
}
node {
  name: "tensor_50_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 9216
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/0/self_attn/qkv_proj/linear_fwd_bf16/570_complex/batch_gemm_0_expand2"
  op: "ExpandDims"
  input: "tensor_50_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_50_/placeholder/1  |  Sizes = [9216,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [56623104, 6144, 2]  |  data = 0, sizeInBytes = 56623104  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xe0000000000  |  userMemorySection(type=Persistent, id=14)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_50_/placeholder/1_c7664  |  Sizes = [1,9216,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [56623104, 56623104, 6144, 2]  |  data = 0, sizeInBytes = 56623104  |  isAliased = tensor_50_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_48_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "fusedTPCNode_15_1_bundle_32/op_0"
  op: "fused_kernel_0xD13FDC66_26_f32"
  input: "fusedTPCNode_15_0"
  input: "model/0/input_layernorm/rsqrt_fwd_f32/566_complex/rsqrt_fwd_f32_0_reshape_TPC_out0"
  input: "tensor_48_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0xf0000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_44_id_19811_model/0/input_layernorm/aten__rsqrt  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001180  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_48_/placeholder/0  |  Sizes = [3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [6144, 2]  |  data = 0, sizeInBytes = 6144  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xc0000000000  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49_id_19819_model/0/input_layernorm/aten__mul_slice_0_0_0_0_0__0__bundle_32_7707  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "model/0/self_attn/qkv_proj/linear_fwd_bf16/570_complex/batch_gemm_0_bundle_32/op_1"
  op: "BatchGemm"
  input: "fusedTPCNode_15_1_bundle_32/op_0"
  input: "model/0/self_attn/qkv_proj/linear_fwd_bf16/570_complex/batch_gemm_0_expand2"
  attr {
    key: "Bundle_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49_id_19819_model/0/input_layernorm/aten__mul_slice_0_0_0_0_0__0__bundle_32_7707  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_50_/placeholder/1_c7664  |  Sizes = [1,9216,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [56623104, 56623104, 6144, 2]  |  data = 0, sizeInBytes = 56623104  |  isAliased = tensor_50_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_51_id_19821_model/0/self_attn/qkv_proj/aten__linear  |  Sizes = [16,1,9216]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [294912, 18432, 18432, 2]  |  data = 0, sizeInBytes = 294912  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xf0000000000  |  userMemorySection(type=Persistent, id=15)  |  "
    }
  }
}
node {
  name: "tensor_51_id_19821_model/0/self_attn/qkv_proj/aten__linear"
  op: "OutputTensor"
  input: "model/0/self_attn/qkv_proj/linear_fwd_bf16/570_complex/batch_gemm_0_bundle_32/op_1"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 9216
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_49_id_19819_model/0/input_layernorm/aten__mul_bundle_32/memcpy/0"
  op: "DmaMemcpy"
  input: "fusedTPCNode_15_1_bundle_32/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49_id_19819_model/0/input_layernorm/aten__mul_slice_0_0_0_0_0__0__bundle_32_7707  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49_id_19819_model/0/input_layernorm/aten__mul  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
}
node {
  name: "tensor_49_id_19819_model/0/input_layernorm/aten__mul"
  op: "OutputTensor"
  input: "tensor_49_id_19819_model/0/input_layernorm/aten__mul_bundle_32/memcpy/0"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_55_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2050
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/slice/573"
  op: "Slice"
  input: "tensor_55_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_55_/placeholder/0  |  Sizes = [16,2050]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131200, 8200, 4]  |  data = 0, sizeInBytes = 131200  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x110000000000  |  userMemorySection(type=Persistent, id=17)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131200, 8200, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_55_/placeholder/0, type = slice, offset: 8196  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice_memcpy_7710_internal"
  op: "StridedDmaViaTranspose"
  input: "model/0/self_attn/rotary_emb/slice/573"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131200, 8200, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_55_/placeholder/0, type = slice, offset: 8196  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice_memcpy_7710  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0x30000  |  "
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reshape/574"
  op: "Reshape"
  input: "tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice_memcpy_7710_internal"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice_memcpy_7710  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0x30000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_59  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice_memcpy_7710, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor-7657"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/575_complex/reduce_max_fwd_i32_0"
  op: "reduce_max_fwd_i32"
  input: "model/0/self_attn/rotary_emb/reshape/574"
  input: "tensor-7657"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "25"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_59  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_57_id_19708_model/0/self_attn/rotary_emb/aten__slice_memcpy_7710, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-7657  |  Sizes = [256]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0x55a1ffcde400, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x1000000df80  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_60  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x30080  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_61  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x30100  |  "
    }
  }
}
node {
  name: "tensor_61"
  op: "OutputTensor"
  input: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/575_complex/reduce_max_fwd_i32_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "tensor_52_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/add_fwd_i32/579_complex/add_fwd_i32_0"
  op: "add_fwd_i32"
  input: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/575_complex/reduce_max_fwd_i32_0"
  input: "tensor_52_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "26"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_60  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x30080  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_52_/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x100000000000  |  userMemorySection(type=Persistent, id=16)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_65_id_19843_model/0/self_attn/rotary_emb/hpu__add  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x120000000000  |  userMemorySection(type=Persistent, id=18)  |  "
    }
  }
}
node {
  name: "tensor_66_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/greater_fwd_i32/580_complex/greater_fwd_i32_0"
  op: "greater_fwd_i32"
  input: "model/0/self_attn/rotary_emb/add_fwd_i32/579_complex/add_fwd_i32_0"
  input: "tensor_66_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "27"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_65_id_19843_model/0/self_attn/rotary_emb/hpu__add  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x120000000000  |  userMemorySection(type=Persistent, id=18)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_66_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x130000000000  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_67_id_19848_model/0/self_attn/rotary_emb/aten__gt  |  Sizes = [1]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1, 1]  |  data = 0, sizeInBytes = 1  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x140000000000  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_67_id_19848_model/0/self_attn/rotary_emb/aten__gt"
  op: "OutputTensor"
  input: "model/0/self_attn/rotary_emb/greater_fwd_i32/580_complex/greater_fwd_i32_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT8
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int8"
    }
  }
}
