node {
  name: "tensor_1_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/embed_tokens/embedding_pt_fwd_bf16/1061_complex/reshape_0"
  op: "Reshape"
  input: "tensor_1_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_1_/placeholder/1  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "i32-1_11454  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_1_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 32064
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/embed_tokens/embedding_pt_fwd_bf16/1061_complex/gather_bf16_2"
  op: "gather_bf16"
  input: "tensor_0_/placeholder/0"
  input: "model/embed_tokens/embedding_pt_fwd_bf16/1061_complex/reshape_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [32064,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [197001216, 6144, 2]  |  data = 0, sizeInBytes = 197001216  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "i32-1_11454  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_1_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "bf16-3_11455  |  Sizes = [16,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isAliased = tensor_2_id_37669_model/embed_tokens/aten__embedding, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/embed_tokens/embedding_pt_fwd_bf16/1061_complex/reshape_4"
  op: "Reshape"
  input: "model/embed_tokens/embedding_pt_fwd_bf16/1061_complex/gather_bf16_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "bf16-3_11455  |  Sizes = [16,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isAliased = tensor_2_id_37669_model/embed_tokens/aten__embedding, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_id_37669_model/embed_tokens/aten__embedding  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "model/range_i32/1062"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_3_id_37674_model/aten__arange  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
}
node {
  name: "tensor_4_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/expand_dims/1065"
  op: "Reshape"
  input: "tensor_4_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_4_/placeholder/0  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_7_id_37722_model/aten__unsqueeze  |  Sizes = [16,1,1,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 8208, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = tensor_4_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/reshape/1068"
  op: "Reshape"
  input: "model/range_i32/1062"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_3_id_37674_model/aten__arange  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11_id_37694_model/aten__view  |  Sizes = [1,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isAliased = tensor_3_id_37674_model/aten__arange, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/range_i32/1069"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12_id_37688_model/aten__arange  |  Sizes = [2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8208, 4]  |  data = 0, sizeInBytes = 8208  |  isAliased = _reshaped_11629, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/greater_fwd_i32/1070_complex/greater_fwd_i32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "model/range_i32/1069"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_id_37688_model/aten__arange  |  Sizes = [2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8208, 4]  |  data = 0, sizeInBytes = 8208  |  isAliased = _reshaped_11629, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11629  |  Sizes = [12,171]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8208, 684, 4]  |  data = 0, sizeInBytes = 8208  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
}
node {
  name: "model/greater_fwd_i32/1070_complex/greater_fwd_i32_0_optimized"
  op: "greater_fwd_i32"
  input: "model/greater_fwd_i32/1070_complex/greater_fwd_i32_0_reshape_TPC_out1"
  input: "model/reshape/1068"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11629  |  Sizes = [12,171]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8208, 684, 4]  |  data = 0, sizeInBytes = 8208  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_11_id_37694_model/aten__view  |  Sizes = [1,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4, 4]  |  data = 0, sizeInBytes = 4  |  isAliased = tensor_3_id_37674_model/aten__arange, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11632  |  Sizes = [12,171]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052, 171, 1]  |  data = 0, sizeInBytes = 2052  |  isAliased = tensor-11627, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "reshape_2_2"
  op: "Reshape"
  input: "model/greater_fwd_i32/1070_complex/greater_fwd_i32_0_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11632  |  Sizes = [12,171]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052, 171, 1]  |  data = 0, sizeInBytes = 2052  |  isAliased = tensor-11627, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor-11627  |  Sizes = [1,1,1,2052]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052, 2052, 2052, 2052, 1]  |  data = 0, sizeInBytes = 2052  |  location = in DRAM  |  dramOffset = 0xa0000002080  |  "
    }
  }
}
node {
  name: "fusedTPCNode_25_2"
  op: "fused_kernel_0x5075943_49_bf16"
  input: "reshape_2_2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor-11627  |  Sizes = [1,1,1,2052]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052, 2052, 2052, 2052, 1]  |  data = 0, sizeInBytes = 2052  |  location = in DRAM  |  dramOffset = 0xa0000002080  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18_id_37700_model/aten__unsqueeze  |  Sizes = [1,1,1,2052]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4104, 4104, 4104, 4104, 2]  |  data = 0, sizeInBytes = 4104  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  "
    }
  }
}
node {
  name: "tensor_27_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "fusedTPCNode_25_3"
  op: "fused_kernel_0xD67545FF_4A_f32"
  input: "fusedTPCNode_25_2"
  input: "model/expand_dims/1065"
  input: "tensor_27_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_18_id_37700_model/aten__unsqueeze  |  Sizes = [1,1,1,2052]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4104, 4104, 4104, 4104, 2]  |  data = 0, sizeInBytes = 4104  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_7_id_37722_model/aten__unsqueeze  |  Sizes = [16,1,1,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 8208, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = tensor_4_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_27_/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32_id_37749_model/hpu__slice_insert  |  Sizes = [16,1,1,2052]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65664, 4104, 4104, 4104, 2]  |  data = 0, sizeInBytes = 65664  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
}
node {
  name: "tensor_32_id_37749_model/hpu__slice_insert"
  op: "OutputTensor"
  input: "fusedTPCNode_25_3"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "fusedTPCNode_25_0"
  op: "fused_kernel_0x58A689BE_47_f32"
  input: "model/embed_tokens/embedding_pt_fwd_bf16/1061_complex/reshape_4"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_id_37669_model/embed_tokens/aten__embedding  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0xf0000000000  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_38_id_37755_model/0/input_layernorm/aten__pow  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/reduce_mean_multi_dim_fwd_f32/1094_complex/reduce_mean_fwd_f32_0_complex/reduce_mean_fwd_f32_0"
  op: "reduce_mean_fwd_f32"
  input: "fusedTPCNode_25_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_38_id_37755_model/0/input_layernorm/aten__pow  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_42  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001080  |  "
    }
  }
}
node {
  name: "tensor_33_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "model/0/input_layernorm/add_fwd_f32/1095_complex/add_fwd_f32_0"
  op: "add_fwd_f32"
  input: "model/0/input_layernorm/reduce_mean_multi_dim_fwd_f32/1094_complex/reduce_mean_fwd_f32_0_complex/reduce_mean_fwd_f32_0"
  input: "tensor_33_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_42  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001080  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_33_/placeholder/0  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xb0000000000  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_43_id_37761_model/0/input_layernorm/hpu__add  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = _reshaped_11633, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/rsqrt_fwd_f32/1096_complex/rsqrt_fwd_f32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "model/0/input_layernorm/add_fwd_f32/1095_complex/add_fwd_f32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_43_id_37761_model/0/input_layernorm/hpu__add  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = _reshaped_11633, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11633  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001100  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/rsqrt_fwd_f32/1096_complex/rsqrt_fwd_f32_0_optimized"
  op: "rsqrt_fwd_f32"
  input: "model/0/input_layernorm/rsqrt_fwd_f32/1096_complex/rsqrt_fwd_f32_0_reshape_TPC_out1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11633  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001100  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11634  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_44_id_37767_model/0/input_layernorm/aten__rsqrt, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/rsqrt_fwd_f32/1096_complex/rsqrt_fwd_f32_0_reshape_TPC_out0"
  op: "StaticReshape"
  input: "model/0/input_layernorm/rsqrt_fwd_f32/1096_complex/rsqrt_fwd_f32_0_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11634  |  Sizes = [1,4,4]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 64, 16, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_44_id_37767_model/0/input_layernorm/aten__rsqrt, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_44_id_37767_model/0/input_layernorm/aten__rsqrt  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001180  |  "
    }
  }
}
node {
  name: "tensor_50_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 9216
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/0/self_attn/qkv_proj/linear_fwd_bf16/1100_complex/batch_gemm_0_expand2"
  op: "ExpandDims"
  input: "tensor_50_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_50_/placeholder/1  |  Sizes = [9216,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [56623104, 6144, 2]  |  data = 0, sizeInBytes = 56623104  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xe0000000000  |  userMemorySection(type=Persistent, id=14)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_50_/placeholder/1_c11635  |  Sizes = [1,9216,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [56623104, 56623104, 6144, 2]  |  data = 0, sizeInBytes = 56623104  |  isAliased = tensor_50_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_48_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "fusedTPCNode_25_1_bundle_58/op_0"
  op: "fused_kernel_0xD13FDC66_48_f32"
  input: "fusedTPCNode_25_0"
  input: "model/0/input_layernorm/rsqrt_fwd_f32/1096_complex/rsqrt_fwd_f32_0_reshape_TPC_out0"
  input: "tensor_48_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "58"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_37  |  Sizes = [16,1,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [196608, 12288, 12288, 4]  |  data = 0, sizeInBytes = 196608  |  location = in DRAM  |  dramOffset = 0xf0000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_44_id_37767_model/0/input_layernorm/aten__rsqrt  |  Sizes = [16,1,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0xd0000001180  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_48_/placeholder/0  |  Sizes = [3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [6144, 2]  |  data = 0, sizeInBytes = 6144  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xc0000000000  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49_id_37775_model/0/input_layernorm/aten__mul_slice_0_0_0_0_0__0__bundle_58_11678  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
}
node {
  name: "model/0/self_attn/qkv_proj/linear_fwd_bf16/1100_complex/batch_gemm_0_bundle_58/op_1"
  op: "BatchGemm"
  input: "fusedTPCNode_25_1_bundle_58/op_0"
  input: "model/0/self_attn/qkv_proj/linear_fwd_bf16/1100_complex/batch_gemm_0_expand2"
  attr {
    key: "Bundle_idx"
    value {
      s: "58"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Parameters"
    value {
      s: "transpose_a=false, transpose_b=true"
    }
  }
  attr {
    key: "fp8BiasIn"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasIn2"
    value {
      s: "0"
    }
  }
  attr {
    key: "fp8BiasOut"
    value {
      s: "0"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49_id_37775_model/0/input_layernorm/aten__mul_slice_0_0_0_0_0__0__bundle_58_11678  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_50_/placeholder/1_c11635  |  Sizes = [1,9216,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [56623104, 56623104, 6144, 2]  |  data = 0, sizeInBytes = 56623104  |  isAliased = tensor_50_/placeholder/1, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_51_id_37777_model/0/self_attn/qkv_proj/aten__linear  |  Sizes = [16,1,9216]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [294912, 18432, 18432, 2]  |  data = 0, sizeInBytes = 294912  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xf0000000000  |  userMemorySection(type=Persistent, id=15)  |  "
    }
  }
}
node {
  name: "tensor_51_id_37777_model/0/self_attn/qkv_proj/aten__linear"
  op: "OutputTensor"
  input: "model/0/self_attn/qkv_proj/linear_fwd_bf16/1100_complex/batch_gemm_0_bundle_58/op_1"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 9216
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_49_id_37775_model/0/input_layernorm/aten__mul_bundle_58/memcpy/0"
  op: "DmaMemcpy"
  input: "fusedTPCNode_25_1_bundle_58/op_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "58"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_49_id_37775_model/0/input_layernorm/aten__mul_slice_0_0_0_0_0__0__bundle_58_11678  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  location = in SRAM  |  sramOffset = 0x1000fffffd050000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_49_id_37775_model/0/input_layernorm/aten__mul  |  Sizes = [16,1,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [98304, 6144, 6144, 2]  |  data = 0, sizeInBytes = 98304  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xd0000000000  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
}
node {
  name: "tensor_49_id_37775_model/0/input_layernorm/aten__mul"
  op: "OutputTensor"
  input: "tensor_49_id_37775_model/0/input_layernorm/aten__mul_bundle_58/memcpy/0"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_55_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/slice/1103"
  op: "Slice"
  input: "tensor_55_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_55_/placeholder/0  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x110000000000  |  userMemorySection(type=Persistent, id=17)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_55_/placeholder/0, type = slice, offset: 8204  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
}
node {
  name: "tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice_memcpy_11681_internal"
  op: "StridedDmaViaTranspose"
  input: "model/0/self_attn/rotary_emb/slice/1103"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_55_/placeholder/0, type = slice, offset: 8204  |  location = in DRAM  |  isSparseLayout  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice_memcpy_11681  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0x30000  |  "
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reshape/1104"
  op: "Reshape"
  input: "tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice_memcpy_11681_internal"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice_memcpy_11681  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  location = in DRAM  |  dramOffset = 0x30000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_59  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice_memcpy_11681, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor-11628"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/1105_complex/reduce_max_fwd_i32_0"
  op: "reduce_max_fwd_i32"
  input: "model/0/self_attn/rotary_emb/reshape/1104"
  input: "tensor-11628"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "25"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_59  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_57_id_37664_model/0/self_attn/rotary_emb/aten__slice_memcpy_11681, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor-11628  |  Sizes = [256]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0x55a3c39edc00, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x1000000df80  |  isStaticParam  |  bufferDtype=float32  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_60  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x30080  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_61  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x30100  |  "
    }
  }
}
node {
  name: "tensor_61"
  op: "OutputTensor"
  input: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/1105_complex/reduce_max_fwd_i32_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "tensor_52_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/add_fwd_i32/1109_complex/add_fwd_i32_0"
  op: "add_fwd_i32"
  input: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/1105_complex/reduce_max_fwd_i32_0"
  input: "tensor_52_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "26"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_60  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x30080  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_52_/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x100000000000  |  userMemorySection(type=Persistent, id=16)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_65_id_37799_model/0/self_attn/rotary_emb/hpu__add  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x120000000000  |  userMemorySection(type=Persistent, id=18)  |  "
    }
  }
}
node {
  name: "tensor_66_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/greater_fwd_i32/1110_complex/greater_fwd_i32_0"
  op: "greater_fwd_i32"
  input: "model/0/self_attn/rotary_emb/add_fwd_i32/1109_complex/add_fwd_i32_0"
  input: "tensor_66_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "27"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_65_id_37799_model/0/self_attn/rotary_emb/hpu__add  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x120000000000  |  userMemorySection(type=Persistent, id=18)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_66_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x130000000000  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_67_id_37803_model/0/self_attn/rotary_emb/aten__gt  |  Sizes = [1]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1, 1]  |  data = 0, sizeInBytes = 1  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x140000000000  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_67_id_37803_model/0/self_attn/rotary_emb/aten__gt"
  op: "OutputTensor"
  input: "model/0/self_attn/rotary_emb/greater_fwd_i32/1110_complex/greater_fwd_i32_0"
  attr {
    key: "dtype"
    value {
      type: DT_INT8
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int8"
    }
  }
}
