node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/embed_tokens/reshape/0"
  op: "Reshape"
  input: "tensor_0_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [16,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_1_id_1746_model/embed_tokens/aten__view  |  Sizes = [16,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "tensor_5_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/reshape/3"
  op: "Reshape"
  input: "tensor_5_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_5_/placeholder/0  |  Sizes = [16,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6_id_1792_model/aten__view  |  Sizes = [16,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "tensor_36_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "model/0/input_layernorm/identity/31"
  op: "Identity"
  input: "tensor_36_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_36_/placeholder/0  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_38  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_58_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reshape/44"
  op: "Reshape"
  input: "tensor_58_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_58_/placeholder/0  |  Sizes = [16,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  isPersistent  |  userMemorySection(type=Persistent, id=17)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_60  |  Sizes = [32768]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "tensor_55_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/identity/43"
  op: "Identity"
  input: "tensor_55_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_55_/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=16)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_57  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "model/range_i32/2"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_4_id_1799_model/aten__arange  |  Sizes = [2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
}
node {
  name: "model/reshape/9"
  op: "Reshape"
  input: "model/range_i32/2"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_4_id_1799_model/aten__arange  |  Sizes = [2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4]  |  data = 0, sizeInBytes = 8192  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13_id_1822_model/aten__view  |  Sizes = [2048,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4, 4]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "model/range_i32/10"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_14_id_1816_model/aten__arange  |  Sizes = [2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
}
node {
  name: "model/greater_fwd_i32/11"
  op: "greater_fwd_i32"
  input: "model/range_i32/10"
  input: "model/reshape/9"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_14_id_1816_model/aten__arange  |  Sizes = [2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_13_id_1822_model/aten__view  |  Sizes = [2048,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8192, 4, 4]  |  data = 0, sizeInBytes = 8192  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_15_id_1824_model/aten__gt  |  Sizes = [2048,2048]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4194304, 2048, 1]  |  data = 0, sizeInBytes = 4194304  |  "
    }
  }
}
node {
  name: "model/constant_bf16/12"
  op: "constant_bf16"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16_id_1806_model/aten__full  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "model/matrix_band_part_fwd_bf16/13"
  op: "matrix_band_part_fwd_bf16"
  input: "model/constant_bf16/12"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_16_id_1806_model/aten__full  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_17_id_1813_model/aten__triu  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "model/cast_i8_to_bf16/14"
  op: "cast_i8_to_bf16"
  input: "model/greater_fwd_i32/11"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_15_id_1824_model/aten__gt  |  Sizes = [2048,2048]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4194304, 2048, 1]  |  data = 0, sizeInBytes = 4194304  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_19  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "model/mult_fwd_bf16/15"
  op: "mult_fwd_bf16"
  input: "model/matrix_band_part_fwd_bf16/13"
  input: "model/cast_i8_to_bf16/14"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17_id_1813_model/aten__triu  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_19  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18_id_1813_model/aten__mul_  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "model/expand_dims/16"
  op: "ExpandDims"
  input: "model/mult_fwd_bf16/15"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_18_id_1813_model/aten__mul_  |  Sizes = [2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20_id_1826_model/aten__unsqueeze  |  Sizes = [1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "model/expand_dims/17"
  op: "ExpandDims"
  input: "model/expand_dims/16"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_20_id_1826_model/aten__unsqueeze  |  Sizes = [1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21_id_1828_model/aten__unsqueeze  |  Sizes = [1,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "tensor_2_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 32064
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/embed_tokens/embedding_pt_fwd_bf16/1"
  op: "embedding_pt_fwd_bf16"
  input: "tensor_2_/placeholder/0"
  input: "model/embed_tokens/reshape/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_/placeholder/0  |  Sizes = [32064,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [197001216, 6144, 2]  |  data = 0, sizeInBytes = 197001216  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_id_1746_model/embed_tokens/aten__view  |  Sizes = [16,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_3_id_1794_model/embed_tokens/aten__embedding  |  Sizes = [16,2048,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [201326592, 12582912, 6144, 2]  |  data = 0, sizeInBytes = 201326592  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "model/slice/18"
  op: "Slice"
  input: "model/expand_dims/17"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_21_id_1828_model/aten__unsqueeze  |  Sizes = [1,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_22_id_1830_model/aten__slice  |  Sizes = [1,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "model/slice/19"
  op: "Slice"
  input: "model/slice/18"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "17"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_22_id_1830_model/aten__slice  |  Sizes = [1,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23_id_1832_model/aten__slice  |  Sizes = [1,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
}
node {
  name: "model/cast_bf16_to_f32/32"
  op: "cast_bf16_to_f32"
  input: "model/embed_tokens/embedding_pt_fwd_bf16/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "18"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_3_id_1794_model/embed_tokens/aten__embedding  |  Sizes = [16,2048,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [201326592, 12582912, 6144, 2]  |  data = 0, sizeInBytes = 201326592  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_40  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
}
node {
  name: "model/broadcast/20"
  op: "Broadcast"
  input: "model/slice/19"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "19"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_23_id_1832_model/aten__slice  |  Sizes = [1,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [8388608, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 8388608  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_24_id_1834_model/hpu__expand  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
}
node {
  name: "model/identity/21"
  op: "Identity"
  input: "model/broadcast/20"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "20"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_24_id_1834_model/hpu__expand  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_25_id_1836_model/aten__clone  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/mult_fwd_f32/35"
  op: "mult_fwd_f32"
  input: "model/cast_bf16_to_f32/32"
  input: "model/cast_bf16_to_f32/32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "21"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_40  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_40  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_41_id_1886_model/0/input_layernorm/aten__pow  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
}
node {
  name: "model/slice/4"
  op: "Slice"
  input: "model/reshape/3"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "22"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6_id_1792_model/aten__view  |  Sizes = [16,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_7_id_1846_model/aten__slice  |  Sizes = [16,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "model/expand_dims/5"
  op: "ExpandDims"
  input: "model/slice/4"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "23"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7_id_1846_model/aten__slice  |  Sizes = [16,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8_id_1848_model/aten__unsqueeze  |  Sizes = [16,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "model/expand_dims/6"
  op: "ExpandDims"
  input: "model/expand_dims/5"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "24"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_8_id_1848_model/aten__unsqueeze  |  Sizes = [16,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_9_id_1850_model/aten__unsqueeze  |  Sizes = [16,1,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "model/slice/22"
  op: "Slice"
  input: "model/identity/21"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "25"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_25_id_1836_model/aten__clone  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_26_id_1838_model/aten__slice  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/reduce_mean_multi_dim_fwd_f32/36"
  op: "reduce_mean_multi_dim_fwd_f32"
  input: "model/0/input_layernorm/mult_fwd_f32/35"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "26"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_41_id_1886_model/0/input_layernorm/aten__pow  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [16,2048,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "model/slice/7"
  op: "Slice"
  input: "model/expand_dims/6"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "27"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9_id_1850_model/aten__unsqueeze  |  Sizes = [16,1,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_id_1852_model/aten__slice  |  Sizes = [16,1,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "model/slice/23"
  op: "Slice"
  input: "model/slice/22"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "28"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_26_id_1838_model/aten__slice  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_27_id_1842_model/aten__slice  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/add_fwd_f32/37"
  op: "add_fwd_f32"
  input: "model/0/input_layernorm/reduce_mean_multi_dim_fwd_f32/36"
  input: "model/0/input_layernorm/identity/31"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "29"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_45  |  Sizes = [16,2048,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_38  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_46_id_1895_model/0/input_layernorm/hpu__add  |  Sizes = [16,2048,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "model/cast_i32_to_bf16/8"
  op: "cast_i32_to_bf16"
  input: "model/slice/7"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "30"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_10_id_1852_model/aten__slice  |  Sizes = [16,1,1,2048]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 8192, 8192, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12  |  Sizes = [16,1,1,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 4096, 4096, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  "
    }
  }
}
node {
  name: "model/slice/24"
  op: "Slice"
  input: "model/slice/23"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "31"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_27_id_1842_model/aten__slice  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_28_id_1844_model/aten__slice  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/rsqrt_fwd_f32/38"
  op: "rsqrt_fwd_f32"
  input: "model/0/input_layernorm/add_fwd_f32/37"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "32"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_46_id_1895_model/0/input_layernorm/hpu__add  |  Sizes = [16,2048,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_47_id_1901_model/0/input_layernorm/aten__rsqrt  |  Sizes = [16,2048,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
}
node {
  name: "model/add_fwd_bf16/25"
  op: "add_fwd_bf16"
  input: "model/slice/24"
  input: "model/cast_i32_to_bf16/8"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "33"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_28_id_1844_model/aten__slice  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_12  |  Sizes = [16,1,1,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [65536, 4096, 4096, 4096, 2]  |  data = 0, sizeInBytes = 65536  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_29_id_1854_model/hpu__add  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
}
node {
  name: "model/constant_f32/27"
  op: "constant_f32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "34"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_33  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/mult_fwd_f32/39"
  op: "mult_fwd_f32"
  input: "model/cast_bf16_to_f32/32"
  input: "model/0/input_layernorm/rsqrt_fwd_f32/38"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "35"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_40  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_47_id_1901_model/0/input_layernorm/aten__rsqrt  |  Sizes = [16,2048,1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 8192, 4, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_48_id_1903_model/0/input_layernorm/aten__mul  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
}
node {
  name: "tensor_30_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/equal_fwd_bf16/26"
  op: "equal_fwd_bf16"
  input: "model/add_fwd_bf16/25"
  input: "tensor_30_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "36"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_29_id_1854_model/hpu__add  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_30_/placeholder/1  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_31_id_1863_model/aten__eq  |  Sizes = [16,1,2048,2048]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [67108864, 4194304, 4194304, 2048, 1]  |  data = 0, sizeInBytes = 67108864  |  "
    }
  }
}
node {
  name: "model/cast_f32_to_bf16/28"
  op: "cast_f32_to_bf16"
  input: "model/constant_f32/27"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "37"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_33  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_34  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/cast_f32_to_bf16/40"
  op: "cast_f32_to_bf16"
  input: "model/0/input_layernorm/mult_fwd_f32/39"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "38"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_48_id_1903_model/0/input_layernorm/aten__mul  |  Sizes = [16,2048,3072]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [402653184, 25165824, 12288, 4]  |  data = 0, sizeInBytes = 402653184  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_50  |  Sizes = [16,2048,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [201326592, 12582912, 6144, 2]  |  data = 0, sizeInBytes = 201326592  |  "
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/45"
  op: "reduce_max_fwd_i32"
  input: "model/0/self_attn/rotary_emb/reshape/44"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "39"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_60  |  Sizes = [32768]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131072, 4]  |  data = 0, sizeInBytes = 131072  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_61  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:1"
    value {
      s: "tensor_62  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reshape/46"
  op: "Reshape"
  input: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/45"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "40"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_61  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_59_id_1931_model/0/self_attn/rotary_emb/aten__max  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/identity/48"
  op: "Identity"
  input: "model/0/self_attn/rotary_emb/reshape/46"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "41"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_59_id_1931_model/0/self_attn/rotary_emb/aten__max  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_65  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/reshape/47"
  op: "Reshape"
  input: "model/0/self_attn/rotary_emb/reduce_max_fwd_i32/45"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "42"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_62  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_63  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_63"
  op: "OutputTensor"
  input: "model/0/self_attn/rotary_emb/reshape/47"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/where_bf16/29"
  op: "where_bf16"
  input: "model/equal_fwd_bf16/26"
  input: "model/cast_f32_to_bf16/28"
  input: "model/slice/24"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "43"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_31_id_1863_model/aten__eq  |  Sizes = [16,1,2048,2048]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [67108864, 4194304, 4194304, 2048, 1]  |  data = 0, sizeInBytes = 67108864  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_34  |  Sizes = [1]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2, 2]  |  data = 0, sizeInBytes = 2  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "tensor_28_id_1844_model/aten__slice  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_32_id_1871_model/aten__masked_fill  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
}
node {
  name: "model/0/input_layernorm/constant_i32/33"
  op: "constant_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "44"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_42  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_51_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/0/input_layernorm/mult_fwd_bf16/41"
  op: "mult_fwd_bf16"
  input: "tensor_51_/placeholder/0"
  input: "model/0/input_layernorm/cast_f32_to_bf16/40"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "45"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_51_/placeholder/0  |  Sizes = [3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [6144, 2]  |  data = 0, sizeInBytes = 6144  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_50  |  Sizes = [16,2048,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [201326592, 12582912, 6144, 2]  |  data = 0, sizeInBytes = 201326592  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_52_id_1909_model/0/input_layernorm/aten__mul  |  Sizes = [16,2048,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [201326592, 12582912, 6144, 2]  |  data = 0, sizeInBytes = 201326592  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/add_fwd_i32/49"
  op: "add_fwd_i32"
  input: "model/0/self_attn/rotary_emb/identity/48"
  input: "model/0/self_attn/rotary_emb/identity/43"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "46"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_65  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_57  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_66_id_1933_model/0/self_attn/rotary_emb/hpu__add  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=18)  |  "
    }
  }
}
node {
  name: "model/slice_insert/30"
  op: "SliceInsert"
  input: "model/identity/21"
  input: "model/where_bf16/29"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "47"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_25_id_1836_model/aten__clone  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_32_id_1871_model/aten__masked_fill  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_35_id_1880_model/hpu__slice_insert  |  Sizes = [16,1,2048,2048]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [134217728, 8388608, 8388608, 4096, 2]  |  data = 0, sizeInBytes = 134217728  |  isPersistent  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
}
node {
  name: "tensor_35_id_1880_model/hpu__slice_insert"
  op: "OutputTensor"
  input: "model/slice_insert/30"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2048
        }
        dim {
          size: 2048
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/0/input_layernorm/cast_i32_to_f32/34"
  op: "cast_i32_to_f32"
  input: "model/0/input_layernorm/constant_i32/33"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "48"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_42  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_43  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_43"
  op: "OutputTensor"
  input: "model/0/input_layernorm/cast_i32_to_f32/34"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "tensor_53_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3072
        }
        dim {
          size: 9216
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "model/0/self_attn/qkv_proj/linear_fwd_bf16/42"
  op: "linear_fwd_bf16"
  input: "model/0/input_layernorm/mult_fwd_bf16/41"
  input: "tensor_53_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "49"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_52_id_1909_model/0/input_layernorm/aten__mul  |  Sizes = [16,2048,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [201326592, 12582912, 6144, 2]  |  data = 0, sizeInBytes = 201326592  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_53_/placeholder/1  |  Sizes = [9216,3072]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [56623104, 6144, 2]  |  data = 0, sizeInBytes = 56623104  |  isPersistent  |  userMemorySection(type=Persistent, id=14)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_54_id_1911_model/0/self_attn/qkv_proj/aten__linear  |  Sizes = [16,2048,9216]  |  bf16  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [603979776, 37748736, 18432, 2]  |  data = 0, sizeInBytes = 603979776  |  isPersistent  |  userMemorySection(type=Persistent, id=15)  |  "
    }
  }
}
node {
  name: "tensor_54_id_1911_model/0/self_attn/qkv_proj/aten__linear"
  op: "OutputTensor"
  input: "model/0/self_attn/qkv_proj/linear_fwd_bf16/42"
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 9216
        }
        dim {
          size: 2048
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "bf16"
    }
  }
}
node {
  name: "tensor_67_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "model/0/self_attn/rotary_emb/greater_fwd_i32/50"
  op: "greater_fwd_i32"
  input: "model/0/self_attn/rotary_emb/add_fwd_i32/49"
  input: "tensor_67_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "50"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_66_id_1933_model/0/self_attn/rotary_emb/hpu__add  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=18)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_67_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=19)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_68_id_1945_model/0/self_attn/rotary_emb/aten__gt  |  Sizes = [1]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1, 1]  |  data = 0, sizeInBytes = 1  |  isPersistent  |  userMemorySection(type=Persistent, id=20)  |  "
    }
  }
}
node {
  name: "tensor_68_id_1945_model/0/self_attn/rotary_emb/aten__gt"
  op: "OutputTensor"
  input: "model/0/self_attn/rotary_emb/greater_fwd_i32/50"
  attr {
    key: "dtype"
    value {
      type: DT_INT8
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int8"
    }
  }
}
