node {
  name: "tensor_13_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2051
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC5284_complex/equal_fwd_i32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "tensor_13_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_13_/placeholder/0  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_9368  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = tensor_13_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC5285_complex/cumsum_fwd_i32_0_complex/cumsum_fwd_i32_0"
  op: "cumsum_fwd_i32"
  input: "tensor_13_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_13_/placeholder/0  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16_id_10619_aten__cumsum  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = _reshaped_9370, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC5287_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "TPC5285_complex/cumsum_fwd_i32_0_complex/cumsum_fwd_i32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_16_id_10619_aten__cumsum  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = _reshaped_9370, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_9370  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "TPC5276"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Reshape5277"
  op: "Reshape"
  input: "TPC5276"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_7  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC5279/DmaBroadcast"
  op: "DmaBroadcast"
  input: "tensor_0_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_9  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_10, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Reshape5280"
  op: "Reshape"
  input: "TPC5279/DmaBroadcast"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_10, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 64  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Concatenate5281"
  op: "Concatenate"
  input: "Reshape5277"
  input: "Reshape5280"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_10  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 64  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11  |  Sizes = [2,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 128  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
}
node {
  name: "tensor_14_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC5284_complex/equal_fwd_i32_0_optimized"
  op: "equal_fwd_i32"
  input: "TPC5284_complex/equal_fwd_i32_0_reshape_TPC_out1"
  input: "tensor_14_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_9368  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = tensor_13_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_14_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_9369  |  Sizes = [4,8204]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32816, 8204, 1]  |  data = 0, sizeInBytes = 32816  |  location = in DRAM  |  dramOffset = 0x20100  |  "
    }
  }
}
node {
  name: "tensor_17_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC5287_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_optimized"
  op: "sub_fwd_i32"
  input: "TPC5287_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_reshape_TPC_out1"
  input: "tensor_17_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_9370  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_17_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_9371  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = _reshaped_9370, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC5288"
  op: "constant_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x28180  |  "
    }
  }
}
node {
  name: "tensor_2_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2051
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC5282"
  op: "gather_nd_mxnet_fwd_i32"
  input: "tensor_2_/placeholder/0"
  input: "Concatenate5281"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_/placeholder/0  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_11  |  Sizes = [2,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 128  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_4_id_10617_hpu__index, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Reshape5283"
  op: "Reshape"
  input: "TPC5282"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_4_id_10617_hpu__index, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_4_id_10617_hpu__index  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_4_id_10617_hpu__index"
  op: "OutputTensor"
  input: "Reshape5283"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC5289_optimized"
  op: "where_i32"
  input: "TPC5284_complex/equal_fwd_i32_0_optimized"
  input: "TPC5288"
  input: "TPC5287_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_9369  |  Sizes = [4,8204]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32816, 8204, 1]  |  data = 0, sizeInBytes = 32816  |  location = in DRAM  |  dramOffset = 0x20100  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_21  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x28180  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "_reshaped_9371  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = _reshaped_9370, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_9378  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = tensor_20, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC5289_reshape_TPC_out0"
  op: "StaticReshape"
  input: "TPC5289_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_9378  |  Sizes = [4,8204]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 32816, 4]  |  data = 0, sizeInBytes = 131264  |  isAliased = tensor_20, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
}
node {
  name: "tensor_20"
  op: "OutputTensor"
  input: "TPC5289_reshape_TPC_out0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2051
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
