node {
  name: "tensor_13_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6619_complex/equal_fwd_i32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "tensor_13_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_13_/placeholder/0  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11353  |  Sizes = [12,2736]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 10944, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = tensor_13_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC6620_complex/cumsum_fwd_i32_0_complex/cumsum_fwd_i32_0"
  op: "cumsum_fwd_i32"
  input: "tensor_13_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_13_/placeholder/0  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x70000000000  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16_id_10619_aten__cumsum  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = _reshaped_11355, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC6622_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_reshape_TPC_out1"
  op: "StaticReshape"
  input: "TPC6620_complex/cumsum_fwd_i32_0_complex/cumsum_fwd_i32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_16_id_10619_aten__cumsum  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = _reshaped_11355, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11355  |  Sizes = [513,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 256, 4]  |  data = 0, sizeInBytes = 131328  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
}
node {
  name: "TPC6611"
  op: "range_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Reshape6612"
  op: "Reshape"
  input: "TPC6611"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_7, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_7  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6614/DmaBroadcast"
  op: "DmaBroadcast"
  input: "tensor_0_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_9  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_10, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Reshape6615"
  op: "Reshape"
  input: "TPC6614/DmaBroadcast"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_10, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 64  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Concatenate6616"
  op: "Concatenate"
  input: "Reshape6612"
  input: "Reshape6615"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_7  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_10  |  Sizes = [1,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_11, type = concat, offset: 64  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11  |  Sizes = [2,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 128  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "tensor_14_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6619_complex/equal_fwd_i32_0_optimized"
  op: "equal_fwd_i32"
  input: "TPC6619_complex/equal_fwd_i32_0_reshape_TPC_out1"
  input: "tensor_14_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11353  |  Sizes = [12,2736]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 10944, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = tensor_13_/placeholder/0, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_14_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x80000000000  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11354  |  Sizes = [12,2736]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32832, 2736, 1]  |  data = 0, sizeInBytes = 32832  |  location = in DRAM  |  dramOffset = 0x80  |  "
    }
  }
}
node {
  name: "tensor_17_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6622_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_optimized"
  op: "sub_fwd_i32"
  input: "TPC6622_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_reshape_TPC_out1"
  input: "tensor_17_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11355  |  Sizes = [513,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 256, 4]  |  data = 0, sizeInBytes = 131328  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_17_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x90000000000  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11356  |  Sizes = [513,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 256, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = _reshaped_11362, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC6624_reshape_TPC_in1"
  op: "Reshape"
  input: "TPC6622_complex/sub_fwd_i32_0_complex/sub_fwd_i32_0_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11356  |  Sizes = [513,64]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 256, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = _reshaped_11362, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11362  |  Sizes = [12,2736]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 10944, 4]  |  data = 0, sizeInBytes = 131328  |  location = in DRAM  |  dramOffset = 0x8100  |  "
    }
  }
}
node {
  name: "TPC6623"
  op: "constant_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x28200  |  "
    }
  }
}
node {
  name: "tensor_2_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6617"
  op: "gather_nd_mxnet_fwd_i32"
  input: "tensor_2_/placeholder/0"
  input: "Concatenate6616"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_/placeholder/0  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_11  |  Sizes = [2,16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [128, 64, 4]  |  data = 0, sizeInBytes = 128  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_12  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_4_id_10617_hpu__index, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "Reshape6618"
  op: "Reshape"
  input: "TPC6617"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  isAliased = tensor_4_id_10617_hpu__index, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_4_id_10617_hpu__index  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_4_id_10617_hpu__index"
  op: "OutputTensor"
  input: "Reshape6618"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6624_optimized"
  op: "where_i32"
  input: "TPC6619_complex/equal_fwd_i32_0_optimized"
  input: "TPC6623"
  input: "TPC6624_reshape_TPC_in1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11354  |  Sizes = [12,2736]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [32832, 2736, 1]  |  data = 0, sizeInBytes = 32832  |  location = in DRAM  |  dramOffset = 0x80  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_21  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x28200  |  "
    }
  }
  attr {
    key: "inputTensor:2"
    value {
      s: "_reshaped_11362  |  Sizes = [12,2736]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 10944, 4]  |  data = 0, sizeInBytes = 131328  |  location = in DRAM  |  dramOffset = 0x8100  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_11363  |  Sizes = [12,2736]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 10944, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = tensor_20, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC6624_reshape_TPC_out0"
  op: "StaticReshape"
  input: "TPC6624_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_11363  |  Sizes = [12,2736]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 10944, 4]  |  data = 0, sizeInBytes = 131328  |  isAliased = tensor_20, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_20  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  location = in DRAM  |  dramOffset = 0xa0000000000  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
}
node {
  name: "tensor_20"
  op: "OutputTensor"
  input: "TPC6624_reshape_TPC_out0"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
