node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "tensor_1_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC72_complex/less_fwd_i32_0"
  op: "less_fwd_i32"
  input: "tensor_0_/placeholder/0"
  input: "tensor_1_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [3]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [12, 4]  |  data = 0, sizeInBytes = 12  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_1_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_id_1718_aten__lt  |  Sizes = [3]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3, 1]  |  data = 0, sizeInBytes = 3  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "TPC73"
  op: "cast_i8_to_f32"
  input: "TPC72_complex/less_fwd_i32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_id_1718_aten__lt  |  Sizes = [3]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [3, 1]  |  data = 0, sizeInBytes = 3  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_4  |  Sizes = [3]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [12, 4]  |  data = 0, sizeInBytes = 12  |  location = in DRAM  |  dramOffset = 0x80  |  "
    }
  }
}
node {
  name: "TPC74_complex/abs_fwd_f32_0"
  op: "abs_fwd_f32"
  input: "TPC73"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_4  |  Sizes = [3]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [12, 4]  |  data = 0, sizeInBytes = 12  |  location = in DRAM  |  dramOffset = 0x80  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_5  |  Sizes = [3]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [12, 4]  |  data = 0, sizeInBytes = 12  |  isAliased = tensor_4, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "TPC75_complex/reduce_sum_fwd_f32_0"
  op: "reduce_sum_fwd_f32"
  input: "TPC74_complex/abs_fwd_f32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_5  |  Sizes = [3]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [12, 4]  |  data = 0, sizeInBytes = 12  |  isAliased = tensor_4, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x100  |  "
    }
  }
}
node {
  name: "TPC77"
  op: "constant_f32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x180  |  "
    }
  }
}
node {
  name: "TPC78_complex/equal_fwd_f32_0"
  op: "equal_fwd_f32"
  input: "TPC75_complex/reduce_sum_fwd_f32_0"
  input: "TPC77"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x100  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_8  |  Sizes = [1]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  location = in DRAM  |  dramOffset = 0x180  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_9  |  Sizes = [1]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1, 1]  |  data = 0, sizeInBytes = 1  |  location = in DRAM  |  dramOffset = 0x200  |  "
    }
  }
}
node {
  name: "TPC79"
  op: "not_fwd_i8"
  input: "TPC78_complex/equal_fwd_f32_0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9  |  Sizes = [1]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1, 1]  |  data = 0, sizeInBytes = 1  |  location = in DRAM  |  dramOffset = 0x200  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_3_id_1720_aten__any  |  Sizes = [1]  |  int8  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1, 1]  |  data = 0, sizeInBytes = 1  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x60000000000  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_3_id_1720_aten__any"
  op: "OutputTensor"
  input: "TPC79"
  attr {
    key: "dtype"
    value {
      type: DT_INT8
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int8"
    }
  }
}
