node {
  name: "tensor_19_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "Identity6469"
  op: "Identity"
  input: "tensor_19_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_19_/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=14)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_21  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_0_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 32064
        }
        dim {
          size: 1
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "Slice6456"
  op: "Slice"
  input: "tensor_0_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_0_/placeholder/0  |  Sizes = [16,1,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  isPersistent  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_1_id_19624_aten__slice  |  Sizes = [16,1,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
}
node {
  name: "Slice6457"
  op: "Slice"
  input: "Slice6456"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_1_id_19624_aten__slice  |  Sizes = [16,1,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_2_id_19626_aten__slice  |  Sizes = [16,1,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
}
node {
  name: "Squeeze6458"
  op: "Squeeze"
  input: "Slice6457"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_2_id_19626_aten__slice  |  Sizes = [16,1,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_3_id_19628_aten__squeeze  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
}
node {
  name: "Slice6459"
  op: "Slice"
  input: "Squeeze6458"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "4"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_3_id_19628_aten__squeeze  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_4_id_19630_aten__slice  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
}
node {
  name: "Identity6460"
  op: "Identity"
  input: "Slice6459"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "5"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_4_id_19630_aten__slice  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_5_id_19632_aten__clone  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
}
node {
  name: "TPC6461"
  op: "softmax_fwd_f32"
  input: "Identity6460"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "6"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_5_id_19632_aten__clone  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  isPersistent  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_6_id_19634_aten___softmax  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
}
node {
  name: "tensor_7_/placeholder/1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6462"
  op: "random_multinomial_fwd_f32"
  input: "TPC6461"
  input: "tensor_7_/placeholder/1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "7"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_6_id_19634_aten___softmax  |  Sizes = [16,32064]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [2052096, 128256, 4]  |  data = 0, sizeInBytes = 2052096  |  isPersistent  |  userMemorySection(type=Persistent, id=6)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_7_/placeholder/1  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=7)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_8_id_19641_hpu__multinomial  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
}
node {
  name: "Squeeze6463"
  op: "Squeeze"
  input: "TPC6462"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "8"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_8_id_19641_hpu__multinomial  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  userMemorySection(type=Persistent, id=8)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_9_id_19645_aten__squeeze  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  "
    }
  }
}
node {
  name: "Slice6464"
  op: "Slice"
  input: "Squeeze6463"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "9"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_9_id_19645_aten__squeeze  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_10_id_19647_aten__slice  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  "
    }
  }
}
node {
  name: "ExpandDims6465"
  op: "ExpandDims"
  input: "Slice6464"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "10"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_10_id_19647_aten__slice  |  Sizes = [16]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4]  |  data = 0, sizeInBytes = 64  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_11_id_19649_aten__unsqueeze  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  "
    }
  }
}
node {
  name: "TPC6467"
  op: "constant_i32"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "11"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_16  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
}
node {
  name: "tensor_22_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "Slice6470"
  op: "Slice"
  input: "tensor_22_/placeholder/0"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "12"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_22_/placeholder/0  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=15)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_23_id_19661_aten__slice  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "Identity6471"
  op: "Identity"
  input: "Slice6470"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "13"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_23_id_19661_aten__slice  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
}
node {
  name: "tensor_12_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2051
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "Concatenate6466"
  op: "Concatenate"
  input: "tensor_12_/placeholder/0"
  input: "ExpandDims6465"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "14"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_12_/placeholder/0  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isPersistent  |  userMemorySection(type=Persistent, id=9)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_11_id_19649_aten__unsqueeze  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_13_id_19651_aten__cat  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  userMemorySection(type=Persistent, id=10)  |  "
    }
  }
}
node {
  name: "tensor_13_id_19651_aten__cat"
  op: "OutputTensor"
  input: "Concatenate6466"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "tensor_17_/placeholder/0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2051
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "Concatenate6468"
  op: "Concatenate"
  input: "tensor_17_/placeholder/0"
  input: "TPC6467"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "15"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_17_/placeholder/0  |  Sizes = [16,2051]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131264, 8204, 4]  |  data = 0, sizeInBytes = 131264  |  isPersistent  |  userMemorySection(type=Persistent, id=12)  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_16  |  Sizes = [16,1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [64, 4, 4]  |  data = 0, sizeInBytes = 64  |  isPersistent  |  userMemorySection(type=Persistent, id=11)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_18_id_19659_aten__cat  |  Sizes = [16,2052]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [131328, 8208, 4]  |  data = 0, sizeInBytes = 131328  |  isPersistent  |  userMemorySection(type=Persistent, id=13)  |  "
    }
  }
}
node {
  name: "tensor_18_id_19659_aten__cat"
  op: "OutputTensor"
  input: "Concatenate6468"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2052
        }
        dim {
          size: 16
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
node {
  name: "TPC6472"
  op: "add_fwd_i32"
  input: "Identity6471"
  input: "Identity6469"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "16"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "tensor_25  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "inputTensor:1"
    value {
      s: "tensor_21  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "tensor_26_id_19665_hpu__add  |  Sizes = [1]  |  int32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [4, 4]  |  data = 0, sizeInBytes = 4  |  isPersistent  |  userMemorySection(type=Persistent, id=16)  |  "
    }
  }
}
node {
  name: "tensor_26_id_19665_hpu__add"
  op: "OutputTensor"
  input: "TPC6472"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "int32"
    }
  }
}
